### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by morimorimokenpi**
LGTM

### CODE REVIEW

**Comment by morimorimokenpi** [comment]
https://media.giphy.com/media/3o7rbJ70sEpdugB3BC/giphy.gif

**Comment by minacon** [comment]
LGTM!!

**Comment by MSuzu190331** [comment]
LGTM

**Comment by naomi-0913** [comment]
thumb_lgtm-weknowmemes-lgtm-orangutan-weknowmemes-generator-54200632

**Comment by nishiokadao** [comment]
LGTMだお٩( 'ω' )و

**Pull request merged**
